name: tests

on:
  pull_request
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      # Login to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.dominicwassef}}
          password: ${{secrets.8b546f8a-4abf-4390-9e41-f209bceee1d7}}
          logout: true
      - run: cd auth && npm install && npm run test:ci